name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh-key.pem
          chmod 400 ssh-key.pem

      - name: Deploy to EC2 and build app
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ubuntu@3.110.37.157  << 'EOF'
            set -e

            cd /home/ubuntu

            # Clone repo if not already present
            if [ ! -d "my-app" ]; then
              git clone https://github.com/Nikhilrajput-12/react.git my-app
            fi

            cd my-app
            git pull origin main

            # Install NVM and Node.js 20.19.0
            if [ ! -d "$HOME/.nvm" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            fi

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            nvm install 20.19.0
            nvm use 20.19.0

            echo "Node version: $(node -v)"
            echo "NPM version: $(npm -v)"

            # Install deps and build
            npm install
            npm run build

            # Deploy build to NGINX directory
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            # Restart NGINX
            sudo systemctl restart nginx
          EOF
