name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the version that matches your dev environment

      - name: Install dependencies
        run: npm ci  # Faster and more reliable than 'npm install'

      - name: Build React app
        run: npm run build

      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh-key.pem
          chmod 400 ssh-key.pem

      - name: Copy build folder to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ssh-key.pem" build/ ubuntu@3.110.218.162 :/home/ubuntu/react-app/build/
